apiVersion: v1
kind: Service
metadata:
  name: control-plane
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: stateless-pg
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    control-plane: controller-manager
    app.kubernetes.io/name: stateless-pg
  type: ClusterIP
  ports:
  - name: control-plane-http
    port: 9090
    targetPort: 9090
    protocol: TCP
  - name: control-plane-https
    port: 9443
    targetPort: 9443
    protocol: TCP
  - name: health-probe
    port: 8081
    targetPort: 8081
    protocol: TCP
