apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stateless-pg-prometheus
  labels:
    app.kubernetes.io/name: stateless-pg
    app.kubernetes.io/managed-by: kustomize
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: stateless-pg-prometheus
subjects:
- kind: ServiceAccount
  name: stateless-pg-prometheus
  namespace: system
