# This rule is not used by the project neon-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the core.stateless-pg.io.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: neon-operator
    app.kubernetes.io/managed-by: kustomize
  name: neoncluster-editor-role
rules:
- apiGroups:
  - core.stateless-pg.io.io
  resources:
  - neonclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.stateless-pg.io.io
  resources:
  - neonclusters/status
  verbs:
  - get
