# This rule is not used by the project neon-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to core.open-neon.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: neon-operator
    app.kubernetes.io/managed-by: kustomize
  name: neoncluster-viewer-role
rules:
- apiGroups:
  - core.open-neon.io
  resources:
  - neonclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.open-neon.io
  resources:
  - neonclusters/status
  verbs:
  - get
