apiVersion: core.stateless-pg.io/v1alpha1
kind: NeonCluster
metadata:
  labels:
    app.kubernetes.io/name: stateless-pg
    app.kubernetes.io/managed-by: kustomize
  name: neoncluster-sample
spec:
  # TODO(user): Add fields here
